### ISSUE TITLE
在后台待机一段时间后切回前台收不到消息，必须手动刷新

### ISSUE THREAD

**Issue by LzNOHentai** [fankes/TSBattery#1]
切后台锁屏待机一段时间后。
后台完全收不到消息，虽然这大概是类似加入黑域绿色守护等APP一样不可避免的，但切回前台也无法收到消息，必须一直手动刷新接收。

**Comment by fankes** [comment]
由于我手头机型有限，麻烦您提供一下出问题的手机型号和系统版本，由于QQ接入了HMS推送，可以完全不需要靠传统耗电的接收消息方式。<br/>
另外请开启“保守模式”尝试能否改善这个问题。

**Comment by fankes** [comment]
在不能确定您的系统的情况下，我无法得知QQ是被系统杀掉了还是自己掉后台的问题，比如MIUI，你需要开启自启动权限才可以使其保留后台避免漏消息。

**Comment by LzNOHentai** [comment]
> 在不能确定您的系统的情况下，我无法得知QQ是被系统杀掉了还是自己掉后台的问题，比如MIUI，你需要开启自启动权限才可以使其保留后台避免漏消息。

机型是小米10Ultra，使用的MIUI最新开发版。
QQ我是在最近任务里锁后台的，正常不使用模块的时候都没有出现掉后台的问题，信息接收正常。
使用模块后看起来进程也没有被杀掉，因为切换进去一样流畅，没有冷启动那个过程，单纯的收不到消息。
或许我得试试打开自启动吧。

**Comment by fankes** [comment]
我测试的机型是一样的，我没有这个问题，请打开自启动权限，否则会有故障，后面会补充说明，感谢反馈。
