### ISSUE TITLE
关于禁止商业用途

### ISSUE THREAD

**Issue by ShadowPower** [fankes/TSBattery#11]
在 README 中提到：
> 本模块完全开源免费，如果好用你可以打赏支持开发，严禁未经许可进行二改贩卖，违者必惩必究。
然而项目附带的 GPLv3 许可协议已经授予了所有用户这一项权利：

> 4. Conveying Verbatim Copies.
>   You may convey verbatim copies of the Program's source code as you
> receive it, in any medium, provided that you conspicuously and
> appropriately publish on each copy an appropriate copyright notice;
> keep intact all notices stating that this License and any
> non-permissive terms added in accord with section 7 apply to the code;
> keep intact all notices of the absence of any warranty; and give all
> recipients a copy of this License along with the Program.
> 
>   You may charge any price or no price for each copy that you convey,
> and you may offer support or warranty protection for a fee.

> 4. 转发完整副本
> 你可以通过任何媒介发布你接收到的本程序的完整源码副本，但要做到：
> 为每一个副本醒目而恰当地发布版权；
> 完整地保留关于本协议及按第七条加入的非许可性条款；
> 完整地保留免责声明；
> 给接收者附上一份本协议的副本。
> 你可以免费或收费转发，也可以选择提供技术支持或品质担保以换取收入。

根据该许可协议的内容，只要用户获得了该程序的副本，则已经被许可了在一定的约束下进行二次贩卖。

对此，我有以下疑问：
1. 该程序是否真的以 GPLv3 许可协议授权给用户？
2. 若以 GPLv3 许可协议授权给用户，请问，在什么情况下才能满足“未经许可”的条件？

**Comment by fankes** [comment]
所以您是想贩卖然后在这里显得您还有文艺吧
