### ISSUE TITLE
QQ、Tim区域，关闭coreservice下面的选项被挡住了

### ISSUE THREAD

**Issue by cqsniha** [fankes/TSBattery#12]
![Screenshot_2022-03-23-13-57-58-994_com fankes tsbattery](https://user-images.githubusercontent.com/98676278/159634270-34859ccd-db0c-44cc-b1f6-520dcf36d599.jpg)

**Comment by cqsniha** [comment]
且无法通过滑动屏幕拖出来

**Comment by fankes** [comment]
系统DPI太大了导致的，这个问题已在最新commit中修复，可clone后自行编译

**Comment by cqsniha** [comment]
> 



> 系统DPI太大了导致的，这个问题已在最新commit中修复，可clone后自行编译
多谢

**Comment by cqsniha** [comment]
多谢
