### ISSUE TITLE
屏蔽QQ升级提醒的功能

### ISSUE THREAD

**Issue by LinnyR** [fankes/TSBattery#14]
求大佬可不可以考虑在模块加上屏蔽QQ升级的功能![IMG_20220331_144346.jpg](https://user-images.githubusercontent.com/38827394/160992808-eb99fbbd-95bb-40e0-9cb1-b8556bc3375f.jpg)

**Comment by fankes** [comment]
这是省电模块，不是QQ功能修改模块，请移步 [QAuxiliary](https://github.com/cinit/QAuxiliary)
