### ISSUE TITLE
应用转生APP影响使用

### ISSUE THREAD

**Issue by 006hjy** [fankes/TSBattery#15]
手机里安装了应用转生APP，但我用的是lsp激活的。进入后弹窗，只能退出，无法配置。麻烦把应用转生警告弹窗去掉

**Comment by 006hjy** [comment]
把警告弹窗设置成可关闭就行。我手机里安装了应用转生从来不用，只是作为软件收藏。

**Comment by fankes** [comment]
没有这种需求，不立项，想要请 fork 自己改代码

**Comment by fankes** [comment]
目前已更改为在你激活模块后，将不会再次检测应用转生，此问题不再做回复
