### ISSUE TITLE
[WIP] 加入 LSPatch 模块激活状态显示

### ISSUE THREAD

**Issue by Hikari-27** [fankes/TSBattery#17]
LSPatch版本:0.3.1(317)
TSBattery版本:3.9.7
QQ版本:8.8.50(2324)
LSPatch修补模式:本地模式、便携模式

现象描述:可以正常使用QA模块，TSBattery一直提示模块未激活

**Comment by fankes** [comment]
模块目前是没有适配除了太极和 LSPosed 以外框架的激活状态显示的，如果功能正常，也写明了只是一个显示状态的说明

**Comment by fankes** [comment]
如果功能正常，后期会加入显示激活状态的功能，如果功能不正常，请提供模块详细日志

**Comment by Hikari-27** [comment]
> 可否在 QQ 的设置里看到 TSBattery 的选项？

可以正常看到并跳转

**Comment by fankes** [comment]
> > 可否在 QQ 的设置里看到 TSBattery 的选项？
> 
> 可以正常看到并跳转

那就后期再加入状态显示了，不影响你使用，不就是模块的目的吗

**Comment by fankes** [comment]
新版本已发布，更新版本即可，LSPatch 不支持激活状态显示，但不影响使用，新版本已将配置功能转移到目标 APP
