### ISSUE TITLE
增加热更新支持

### ISSUE THREAD

**Issue by ZQDesigned** [fankes/TSBattery#18]
每次更新QQ/微信版本后，都需要同时更新一次模块，略显麻烦一点。可以增加一个像微X模块或曾经的小菜豆（QQ模块）那样的热更新适配文件的功能，避免每次都需要更新模块带来的麻烦。

**Comment by fankes** [comment]
这个不在考虑范围内，因为每次模块更新都是顺带修复 BUG，而且热更新不稳定，通过 github 即使是 cdn也不难保证完全正常访问，所以不考虑。
