### ISSUE TITLE
[WIP] 新快捷操作无法进入 微信 TSBattery界面

### ISSUE THREAD

**Issue by sky96111** [fankes/TSBattery#24]
LineageOS 19-20220922-NIGHTLY-kebab
LSPosed 1.8.4 
TSBattery 4.0
微信 8.0.27非play版
作用域已选择QQ和微信。

点击TSBattery 快捷操作中的 微信 选项，只会进入微信主界面，而不会进入TSBattery设置界面。且微信设置中右上角未出现TSBattery图标，无法对其进行设置。

LSPosed日志：https://1drv.ms/u/s!AszSQqG8gUTQg9t85F-aH5lljSNrrg?e=BVRb6l

**Comment by fankes** [comment]
没看到微信的模块激活，请重新激活模块并重启微信，如果还不行重启手机

**Comment by sky96111** [comment]
已尝试：关闭所有其他模块后重启、作用域取消微信后重启再启用、作用域中重新优化微信并重启，无效。

这是问题出现的录屏：https://1drv.ms/v/s!AszSQqG8gUTQg9t9Mk8zVUHfg015rw?e=JQPF37
QQ可以正常打开TSB设置界面，微信不行。
scopes.txt中可以看到com.tencent.mm在作用域里，同以微信为作用域的模块 [指纹支付](https://github.com/eritpchy/FingerprintPay) 却正常生效了，所以怀疑不是LSPosed的问题

**Comment by fankes** [comment]
我目前使用以下设备能够正常工作：
微信版本：8.0.27(2220)、8.0.28(2240)
框架：LSPosed 1.8.4
- 小米 10 至尊纪念版 MIUI 13 22.9.20 开发内测版 Android 12
- 一加 9 Pro ColorOS 12.1 Android 12

**Comment by sky96111** [comment]
第一份log是关闭其他模块、清空日志后重启抓的。这里还有一份开启其他模块、运行了几个小时的日志：
https://1drv.ms/u/s!AszSQqG8gUTQg9t_8MBIbqg9V3E6eQ?e=Por58p

**Comment by fankes** [comment]
我调了一下我这也能复现了，别急，今晚修

**Comment by fankes** [comment]
找不到原因，我刚才调试的过程就坏了，然后重新下回了4.0版本再试了一下还是坏的，是不是云控禁用Hook功能了

**Comment by fankes** [comment]
微信自己的所有 Hook 点都挂不上，只能挂系统的，太奇怪了这个问题

**Comment by fankes** [comment]
解决方案，下载微X模块，激活一下，然后再打开，然后我这里微X模块也装载失败，不知道是不是微信热更新了什么东西，但是模块能用了

**Comment by fankes** [comment]
不排除可能是 LSPosed 的问题，但是我测试不出来，也找不到有效日志，但是 hook 点就是不生效，也挂不上，重新开关两个模块后，又能挂上了

**Comment by fankes** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/37344460/193073645-b1a5ec77-40ab-4213-8309-1d021a504d2a.png">
 问题就在，Hook 点挂不上，但是打印日志能看到

**Comment by fankes** [comment]
问题无法定位，经过测试任何 Hook 都可能对微信失效，解决方案为，勾选与微信作用域有关的模块 (例如 WX 模块) 并重启，TSBattery 就能生效了，无法定位问题，这应该不是模块所能涉及到的问题，而是上游框架可能有问题或微信有反 Hook 功能

**Comment by sky96111** [comment]
很有可能是LSPosed的问题，可以帮忙向LSPosed提一下issue吗？我不是模块开发者，能提供的帮助有限

**Comment by fankes** [comment]
> 很有可能是LSPosed的问题，可以帮忙向LSPosed提一下issue吗？我不是模块开发者，能提供的帮助有限

抱歉，我也不能提供有效的反馈，目前可能的问题就是微信的 hook 点可能比较特殊，我也没研究过
