### ISSUE TITLE
请求适配QQ新版8.9.20

### ISSUE THREAD

**Issue by twoone-3** [fankes/TSBattery#25]
如题

**Comment by fankes** [comment]
早已适配了，详见提交记录，我没发 Release，请自行克隆代码编译，项目结构在做调整，结束后才会更新。
提问前首先需要具备明亮的视力以节省彼此宝贵的时间。

**Comment by pa733** [comment]
> 早已适配了，详见提交记录，我没发 Release，请自行克隆代码编译，项目结构在做调整，结束后才会更新。
> 提问前首先需要具备明亮的视力以节省彼此宝贵的时间。

回答前首先需要具备足够的智力以降低大家的血压。
如果一个项目所有者把所有问题归于虚心请教的人的身上，那么我认为这个项目是失败的。
按照你的说法，为什么不叫大家自己pr呢？
pr啥都有。
乐

**Comment by fankes** [comment]
顺便说一句，没有哪个开发者喜欢免费用爱发电，我有自己的事情要做，维护项目都是按自己的需求走，我没有什么大无畏的开源无私精神，也不会有，维护都是义务外的事情，开源出来就是为了让更多人得以学习，有伸手求更新的功夫不如自己去动动手，就这么简单，多说无益。

**Comment by fankes** [comment]
已添加自动构建功能，可前往 [这里](https://github.com/KitsunePie/AppErrorsTracking/actions/workflows/commit_ci.yml) 查看 CI 自动构建版本，可优先体验新版本相关功能，项目结构在做调整，结束后才会发布稳定版。
