### ISSUE TITLE
[Feature] actions自动构建

### ISSUE THREAD

**Issue by youpuhe** [fankes/TSBattery#26]
建议像[这个commit](https://github.com/pa733/TSBattery/commit/0c241ea7e70d3ab7d09be80b66c496a775cb10bb)一样加入workflow文件以在github actions中自动构建TSBattery。
抱歉打扰了，其实我本来想交pr的，但是[我大号](https://github.com/pa733)被您block了交不了，但又因为workflow已经写好了，所以交了个issue。

**Comment by fankes** [comment]
抱歉，最近 spam 比较多，没看就处理掉了，这个我是后期准备加 ci的，因为涉及到版本号问题，暂时没想搞，最近在备考比较忙，想等一切都搞好了再来处理这个项目，还是谢谢。

**Comment by fankes** [comment]
我是不喜欢有一些伸手党不去看就来开 issues 的 (可能是最近被酷安一些让的回复 ptsd 了)，那会我也没看是谁就直接block了，现已解除，抱歉。另外，这个项目我是后期会重新维护的，现在实在是没时间，还请谅解。

**Comment by fankes** [comment]
已添加此功能，可前往 [这里](https://github.com/KitsunePie/AppErrorsTracking/actions/workflows/commit_ci.yml) 查看 CI 自动构建版本。
