### ISSUE TITLE
Bug QQ设置内不显示TSB设置菜单

### ISSUE THREAD

**Issue by A1Panda** [fankes/TSBattery#28]
QQ版本：8.9.28（3700）
太极：10.1.0

**Comment by A1Panda** [comment]
TSB版本：4.2

**Comment by A1Panda** [comment]
![Screenshot_20230116_001548_com tencent mobileqq](https://user-images.githubusercontent.com/59989747/212552688-2e4cbb0e-5c20-47fe-ad9a-2b672fe9e47a.jpg)

**Comment by A1Panda** [comment]
![Uploading Screenshot_20230116_001638_com.fankes.tsbattery.jpg…]()

**Comment by A1Panda** [comment]
![Screenshot_20230116_001638_com fankes tsbattery](https://user-images.githubusercontent.com/59989747/212552800-c77d6e8e-5c00-40bb-a4d1-0ec2b2a2af85.jpg)

**Comment by fankes** [comment]
太极需要审核，审核不是我提交的，未生效就是没有人提交审核，该问题不再回复，不想等待可以去用 LSPatch。
