### ISSUE TITLE
更新后qq设置内无TSBettery项

### ISSUE THREAD

**Issue by rain-0** [fankes/TSBattery#29]
更新到4.2版本后qq设置内就没有TSBettery项了
![Screenshot_20230125_192715_com tencent mobileqq_edit_342284558280](https://user-images.githubusercontent.com/47851758/214552105-4c067db8-2f14-4706-84d2-f5d156212a47.jpg)
回滚4.1版本也无效
qq版本8.9.28 运行环境太极 模块已激活
![Screenshot_20230125_192902_com fankes tsbattery](https://user-images.githubusercontent.com/47851758/214552272-b0394add-1ad3-42f8-8f92-2358594a96c1.jpg)

**Comment by fankes** [comment]
已知可能是太极引擎对更新版本后的的模块可能坏了。
另外：太极问题请找太极相关渠道解决，这不是模块的问题，此类问题不予受理，也无义务受理，谢谢，如你认为这真的是模块的问题，反馈请携带有效问题日志。
