### ISSUE TITLE
qq新版本未适配

### ISSUE THREAD

**Issue by SauronSkywalker** [fankes/TSBattery#35]
### 模块版本

4.25

### 作用域 APP

QQ

### 作用域 APP 版本

8.9.63

### Android 版本

13

### Xposed 框架名称与版本号

.8.6

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

无

### 详细描述问题发生的具体原因

未适配qq8.9.63，界面直接提示未适配

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

1

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
请勿提交与模板不符的问题类型，新版本有时间会适配
