### ISSUE TITLE
[问题与 BUG 反馈] (与微X模块的朋友圈防撤回功能冲突)

### ISSUE THREAD

**Issue by ByChan** [fankes/TSBattery#36]
### 模块版本

4.25

### 作用域 APP

微信

### 作用域 APP 版本

8.0.33 谷歌版

### Android 版本

13

### Xposed 框架名称与版本号

LSPosed 1.8.6（6712）

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

微X模块 2.40最新版本

### 详细描述问题发生的具体原因

实测几次了，开启省电后朋友圈防撤回功能无效

1、正常情况下，手机放置3小时不适用

2、3小时后另一台手机发两条朋友圈，一条1分钟内删除，一条30分钟后删除

3、两条朋友圈都不显示，微X模块没有捕捉到

微X模块已经设置 保持唤醒状态  + 自动加载朋友圈动态

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by ByChan** [comment]
补充：微信使用的是谷歌8033正式版   [v8.0.33.2306 微信谷歌版]

**Comment by fankes** [comment]
不负责且没义务修复其它模块产生的问题，如果发生问题建议先关闭省电功能，因为目前也没有明显的实际效果，请等后期再更新
