### ISSUE TITLE
微信找不到设置入口

### ISSUE THREAD

**Issue by PHCSJC** [fankes/TSBattery#37]
### 模块版本

4.3

### 作用域 APP

微信

### 作用域 APP 版本

8.0.38

### Android 版本

12

### Xposed 框架名称与版本号

LSPosed 1.8.6

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

没有

### 详细描述问题发生的具体原因

QQ可以看到模块入口，说明root lsposed 模块是正常工作的，但微信就是没有入口，手机是k50 android12 miui13

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [x] 我确保上述信息准确无误

**Comment by fankes** [comment]
如果你的近视加深了，你应该去更换一个更好一点的镜片。

![Screenshot_2023-07-26-09-35-06-771_com.github.android-edit.jpg](https://github.com/fankes/TSBattery/assets/37344460/b7ef2b99-fa22-4298-b933-d2d046fda77a)
