### ISSUE TITLE
lspatch下模块偶尔不正常工作

### ISSUE THREAD

**Issue by Enmmma** [fankes/TSBattery#38]
### 模块版本

4.4

### 作用域 APP

QQ

### 作用域 APP 版本

QQ 8.9.89

### Android 版本

12

### Xposed 框架名称与版本号

lspatch

### 系统是否已 Root

否

### 与当前作用域 APP 同作用域的 Xposed 模块

QA，mipush

### 详细描述问题发生的具体原因

有时在QQ设置界面点击tsb，会黑屏较长时间，其他使用场景没有发现问题

### 提供模块问题 Log 或必要 Log

请问log在哪里找

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
你应该不经常需要去打开设置界面，免 root 框架肯定会有一些问题存在，由于不能确定问题，该问题不能修复且不会修复。
