### ISSUE TITLE
[问题与 BUG 反馈] 微信8.0.45(2521)内模块入口位置错位

### ISSUE THREAD

**Issue by 6ur9er** [fankes/TSBattery#39]
### 模块版本

4.4 ci374ffaa

### 作用域 APP

微信

### 作用域 APP 版本

8.0.45(2521)

### Android 版本

13

### Xposed 框架名称与版本号

LSPosed 1.9.2(7024)

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

TSBattery，闰二月，微X模块，HookVip，add fuction for Msg，FunBox

### 详细描述问题发生的具体原因

微信设置页内模块入口位置错位，无功能异常
![微信图片_20240124173819](https://github.com/fankes/TSBattery/assets/103239502/06e02be9-f5b2-45df-98f3-ca06be7a9612)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

[LSPosed_2024-01-24T17_36_15.391767.zip](https://github.com/fankes/TSBattery/files/14036322/LSPosed_2024-01-24T17_36_15.391767.zip)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
检查是否开了强制平板模式，如果是那无解

**Comment by 6ur9er** [comment]
没有开启平板模式，但是我的系统DPI有调节到378

**Comment by fankes** [comment]
那应该会触发平板模式，目前并没有适配平板模式，我个人认为这应该没什么大问题，就不去调无意义的界面了

**Comment by 6ur9er** [comment]
好的，谢谢您
