### ISSUE TITLE
一定时间后停止微信的appbrand进程

### ISSUE THREAD

**Issue by koolcandy** [fankes/TSBattery#41]
### 模块版本

4.4

### 作用域 APP

微信

### 作用域 APP 版本

微信 8.0.47

### Android 版本

14

### Xposed 框架名称与版本号

lsp 1.9.2

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

润二月

### 详细描述问题发生的具体原因

可以考虑一定时间后停止微信的appbrand进程

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
请不要使用问题反馈的模版提功能建议，建议你重新开一个 issue
