### ISSUE TITLE
[问题与 BUG 反馈] QQ设置隐私页面无法打开，会导致QQ闪退

### ISSUE THREAD

**Issue by hsiayuchih** [fankes/TSBattery#44]
### 模块版本

4.4-最新CI版

### 作用域 APP

QQ

### 作用域 APP 版本

QQ 9.0.65

### Android 版本

14

### Xposed 框架名称与版本号

Lspatch

### 系统是否已 Root

否

### 与当前作用域 APP 同作用域的 Xposed 模块

QA

### 详细描述问题发生的具体原因

已验证内嵌此模块后会导致QQ设置页面中的隐私选项无法打开，点开隐私选项QQ即闪退

### 提供模块问题 Log 或必要 Log

Lspatch好像无法查看该模块log

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
没有 log 的问题无法处理，请使用其它手段获取有效 log 后重新反馈
