### ISSUE TITLE
tim可用，qq闪退，微信未测试

### ISSUE THREAD

**Issue by buyioMC** [fankes/TSBattery#49]
### 模块版本

4.4

### 作用域 APP

QQ

### 作用域 APP 版本

QQ 9.10

### Android 版本

14

### Xposed 框架名称与版本号

lspatch 1.9.2

### 系统是否已 Root

否

### 与当前作用域 APP 同作用域的 Xposed 模块

QAuxiliary 1.5.1 XAutoDaily 3.0.27

### 详细描述问题发生的具体原因

使用lspatch安装了官网下载的qq 9.10版本，安装了QAuxiliary 1.5.1和XAutoDaily 3.0.27和TSBattery 4.4模块，点击TSBattery选项后无响应，最后闪退，但是同样的模块在tim上可以正常使用

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

使用lspatch嵌入模块，无法查看日志，但我确认上面写的准确无误

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
请使用 ci 版本，不再修复内置模块的各种问题
