### ISSUE TITLE
QQ打开TSBattery闪退

### ISSUE THREAD

**Issue by xiwanzi** [fankes/TSBattery#50]
### 模块版本

4.4

### 作用域 APP

QQ

### 作用域 APP 版本

9.1.10.20545

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed1.10.1(7118)

### 系统是否已 Root

是

### 与当前作用域 APP 同作用域的 Xposed 模块

QA

### 详细描述问题发生的具体原因

从软件内的快速跳转无法跳转到QQ，而在QQ的设置页面中打开会直接闪退，当前Android15（上面没法选）

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=654   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=269484032 cmp=ComponentInfo{com.fankes.tsbattery/com.fankes.tsbattery.ui.activity.MainActivity} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=639   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.android.settings/com.android.settings.MainSettings} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=663   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.VIEW flag=268435456 cmp=ComponentInfo{mark.via/mark.via.Shell} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=649   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.github.kr328.clash/com.github.kr328.clash.MainActivity} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=661   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.tencent.mm/com.tencent.mm.ui.LauncherUI} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=634   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.coolapk.market/com.coolapk.market.view.main.MainActivity} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=640   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.houvven.guise/com.houvven.guise.ui.MainActivityAlias} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=638   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{bin.mt.plus/bin.mt.plus.MainLightIcon} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=628   userId=0   windowMode=0   baseIntent=Intent { act=null flag=268828672 cmp=ComponentInfo{com.miui.voiceassist/com.xiaomi.voiceassistant.mainui.home.FloatActivity} }
11-08 23:41:59.750  5038  6195 E ActivityManagerWrapper:  mainTaskId=626   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{tv.danmaku.bili/tv.danmaku.bili.MainActivityV2} }
11-08 23:41:59.751  5038  6195 D WorldCirculate: getWorldCirculateInfo, taskInfo.baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.tencent.mobileqq/.activity.SplashActivity }, displayId=-1, but get Display failed
11-08 23:41:59.752  5038  6195 D WorldCirculate: getWorldCirculateInfo, taskInfo.baseIntent=Intent { flg=0x10060000 cmp=com.miui.voiceassist/com.xiaomi.voiceassistant.mainui.home.FloatActivity }, displayId=-1, but get Display failed
11-08 23:41:59.752  5038  6195 D TaskSnapshotCompatVV: getIsInvalidateFromTaskSnapshot, return, mTaskSnapshot=null, mTaskSnapshotClazz=null
11-08 23:41:59.753  5038  6195 D RecentsModel: onTaskStackChangedBackground    MSG_TASK_STACK_CHANGE
11-08 23:41:59.753  5038  6195 W RecentsModel: getRunningTask   taskInfo=TaskInfo{userId=0 taskId=633 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[org.lsposed.manager.LAUNCH_MANAGER] flg=0x10000000 pkg=com.android.shell cmp=com.android.shell/.BugreportWarningActivity } baseActivity=ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity} topActivity=ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity} origActivity=null realActivity=ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity} numActivities=1 lastActiveTime=1844664 supportsSplitScreenMultiWindow=true supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=200 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@c5a82ff} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{6ada8cc com.android.shell.BugreportWarningActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityInMiuiSizeCompat=false topActivityEligibleForLetterboxEducation= falseisLetterboxEducationEnabled= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2400 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatTaskInfo=CameraCompatTaskInfo { cameraCompatControlState=hidden freeformCameraCompatMode=inactive}} isImmersive=false mTopActivityRequestOrientation=-1 mBehindAppLockPkg=null mOriginatingUid=0 isEmbedded=false shouldBeVisible=true mIsCastMode=false mTopActivityMediaSize=null mTopActivityRecordName=ActivityRecord{de0a444 u0 com.android.shell/.BugreportWarningActivity t633} mTopActivityOrientation=-1}
11-08 23:41:59.753  5038  6195 D RecentsModel: preloadRecents runningTaskId:633, mCurrentRunningTaskId:-1, mRecentsTaskLoadPlan=com.android.systemui.shared.recents.model.RecentsTaskLoadPlan@b273715
11-08 23:41:59.754  5038  6195 E ActivityManagerWrapper: get all recent tasks force including 633
11-08 23:41:59.754  1898 14485 E sensors-hal: handle_sns_client_event:52, Dsd_event: ts=1844640675142, event=0.000000
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper: getRecentTasksForceIncludingTaskIdIfValid: getRecentTasks: size=14
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper:  mainTaskId=633   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity} }
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper:  mainTaskId=635   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.microsoft.emmx/com.microsoft.ruby.Main} }
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper:  mainTaskId=664   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=271581184 cmp=ComponentInfo{com.tencent.mobileqq/com.tencent.mobileqq.activity.SplashActivity} }
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper:  mainTaskId=632   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{org.lsposed.lspatch/org.lsposed.lspatch.ui.activity.MainActivity} }
11-08 23:41:59.756  5038  6195 E ActivityManagerWrapper:  mainTaskId=654   userId=0   windowMode=1   baseIntent=Intent { act=android.intent.action.MAIN flag=269484032 cmp=ComponentInfo{com.fankes.tsbattery/com.fankes.tsbattery.ui.activity.MainActivity} }

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
没看到有效日志，修不了+本人上班较忙，之前的问题是资源注入寄了，模块正常运行能赛博省电就可以了，UI 只是显示作用，问题不大 (已摆烂)
